baseURL = "https://princetonstrong.online"
languageCode = "en-us"
theme = "glim-midnight"

[params]
    title = "Terok Noir"
    phrases = ["DevSecOps", "Futurist", "Cloud", "Code", "Linux"]
    links = [
    {name = "Github", url = "https://github.com/borninthedark/", newTab = true},
    {name = "Blog", url = "https://blog.princetonstrong.online/"},
    {name = "Gallery", url = "https://gallery.princetonstrong.online"},
    {name = "Wiki", url = "https://wiki.princetonstrong.online"},
    
    ] 
    backgroundVideo= "bg.mp4"
    footer = "Borrowed with ❤️ by <a href='https://princetonstrong.online/' target='_blank'>Princeton A. Strong</a>"