baseURL = "https://princetonstrong.online"
languageCode = "en-us"
theme = "glim-midnight"

[params]
    title = "Deep Space Mine"
    phrases = ["DevSecOps", "Microservices", "Python", "*Nix"]
    links = [
    {name = "Github", url = "https://github.com/borninthedark/", newTab = true},
    {name = "Blog", url = "https://blog.princetonstrong.online/"},
    ] 
    backgroundVideo= "bg.mp4"
    footer = "Engineers thrive in the imperfect & unknown. - <a href='https://blog.princetonstrong.online/' target='_blank'>Princeton A. Strong</a>"
